/*Name - Priyank Pawar
id - 100949832
In class assignment - 7
date - 22/03/2024
subject - INFT 1105 INTRODUCTION TO DATABASES*/


/*QUESTION 1
 WRITE SQL DECLARE AND SELECT STATEMENTS THAT DEFINE AN INTEGER, ACCEPT A PLAYER ID AND THEN LISTS ALL THE GOALS THAT PLAYER HAS SCORED INCLUDING THE GAMENUM AND THE DATE.*/
 DECLARE @playerid INT;
SET @playerid = 2143578
SELECT 
g.gameNum, 
g.gamedatetime,  
gs.numgoals
FROM games g
INNER JOIN goalScorers gs ON g.gameID = gs.gameID
where gs.playerid=@playerid

/*QUESTION 2
WRITE A SELECT STATMENT TO SHOW HOW MANY TIMES EACH SHIRT NUMBER (JerseyNumber) HAS BEEN ASSIGNED TO A PLAYER.*/
SELECT jerseynumber, COUNT(DISTINCT playerid) as "number of players"
FROM rosters
GROUP BY jerseynumber
/*QUESTION 3
WRITE THE SQL STATEMENTS TO 
1) ADD YOUR SELF AS A PLAYER TO THE DATABASE WITH YOUR REGNUMBER BEING YOUR STUDENTID 
3) ADD YOURSELF TO THE TEAM*/
INSERT INTO players (playerid, regnumber, firstname)
VALUES (2, 100949832, 'Priyank');
SELECT FIRSNAME='PRIYANk',
PLAYERID=2,
re=100949832
from players
/* 2) ADD A TEAM TO THE DATABASES CALLED INFT1105*/
INSERT INTO teams (teamid,teamname)
VALUES(500,'INFT1105')
/* 3)ADD YOURSELF TO THE TEAM!*/
INSERT INTO teams(teamname,teamid )
VALUES ('INFT1105',100949832);

















